### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by Madriix** [unrealircd/unrealircd-webpanel#26]
Hi, I deleted my "unrealircd-webpanel" folder from the ftp, and when I try to download the latest update, it won't install and I'm getting errors. As a result, I am unable to install unrealircd-webpanel because the entire configuration system is no longer editable.

What should I put in config.php?

I have Php 8.1 version.

Best regards.

**Comment by syzop** [comment]
There has been a lot of work past week. Users no longer manually edit config.php, instead of that we now have a setup screen that guides users. There was also a major bugfix an hour ago that fixes an HTTP 500 error, so be sure to grab the latest version.

The installation procedure changed quite a bit. Be sure to check the latest info at: https://www.unrealircd.org/docs/UnrealIRCd_webpanel#Configuring_the_webpanel especially with regards to permissions and so on.

If there are still mysterious blank screens or fatal HTTP errors, then check the apache error log and let us know the errors. But again, be sure to use latest version.

**Comment by Madriix** [comment]
@syzop Ok I tried again, but I still have the same error:

> UnrealIRCd Admin Panel Configuration and Setup
> 
> Fatal error: Uncaught Error: Call to undefined function opcache_invalidate() in /home/x/labs.x.com/unrealircd-webpanel/common.php:121 Stack trace: #0 /home/x/labs.x.com/unrealircd-webpanel/settings/install.php(133): write_config_file() #1 {main} thrown in /home/x/labs.xxxcom/unrealircd-webpanel/common.php on line 121


then when I go to the home page I have this:

> Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxxxxnner_unrealircdwebpanel.unreal_settings' doesn't exist in /home/xxxxxx/unrealircd-webpanel/plugins/sql_auth/SQL/settings.php:7 Stack trace: #0 /home/xxxxxx/unrealircd-webpanel/plugins/sql_auth/SQL/settings.php(7): PDO->query('SELECT * FROM u...') #1 /home/xxxxxx/unrealircd-webpanel/common.php(72): DbSettings::get() #2 /home/xxxxxx/unrealircd-webpanel/common.php(265): read_config_db() #3 /home/xxxxxx/unrealircd-webpanel/index.php(2): require_once('/home/xxxxxx...') #4 {main} thrown in /home/xxxxxx/unrealircd-webpanel/plugins/sql_auth/SQL/settings.php on line 7


My database and username are the same from cpanel

**Comment by syzop** [comment]
Thanks for the report and the good error log, fixed now! :)

**Comment by Madriix** [comment]
I just deleted the "unrealircd-webpanel" folder and re-uploaded it and it's good everything is installed. It's beautiful.
On the other hand, you should know that Firefox kept asking me to save the login/password for the connection, it did that for each form

Maybe you should put this in the `<form>` tag:
`<form autocomplete="off">`
I never tested
